In [1]:
import numpy 
a=numpy.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [2]:
print (a)

[1 2 3 4]


In [3]:
m=[7,8,9]
n=numpy.array(m)
n

array([7, 8, 9])

In [5]:
c=numpy.arange(5)
c

array([0, 1, 2, 3, 4])

In [6]:
import numpy as np
d=np.arange(1,15,3)
d

array([ 1,  4,  7, 10, 13])

In [7]:
e=np.ones(5)
e

array([1., 1., 1., 1., 1.])

In [8]:
f=np.zeros(5)
f

array([0., 0., 0., 0., 0.])

In [10]:
j=np.empty(4)
j

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.29061074e-306])

In [11]:
print(a.ndim)

1


In [13]:
print(c.shape)

(5,)


In [14]:
print(a.shape)

(4,)


In [22]:
a=([0,1,2,3,4,5])
print(a)


[0, 1, 2, 3, 4, 5]


In [21]:
b= a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [6]:
import numpy as np
f=np.array([1,3,5,])
print(f)

[1 3 5]


In [7]:
print(len(f))

3


In [2]:
print(a.shape)

(4,)


In [13]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [14]:
print(a.shape)

(4,)
